language: go
go:
  - 1.10.x
  - master

before_script:
  - mysql -e 'CREATE DATABASE gom;'
  - psql -c 'CREATE DATABASE gom;' -U postgres

install:
  - env GO111MODULE=on go get github.com/onsi/ginkgo/...
  - env GO111MODULE=on go build ./...

script:
  - env GO111MODULE=on ginkgo -r -v -covermode=atomic

after_success:
  - script/cover.sh
  - bash <(curl -s https://codecov.io/bash)