language: go
go:
  - "1.11.x"

before_script:
  - mysql -e 'CREATE DATABASE gom;'
  - psql -c 'CREATE DATABASE gom;' -U postgres

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/onsi/ginkgo/...
  - go build ./...

script:
  - ginkgo -r -v -covermode=atomic

after_success:
  - script/cover.sh
  - bash <(curl -s https://codecov.io/bash)
